### ISSUE TITLE
Tension between three conflicting goals

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/remake-slides#7]
1. Run fast
1. Run reproducibly
1. Run repeatedly (for work in progress)

## Fast and reproducible, but difficult to repeat

Example: Waterfall process

## Fast and repeatable, but reproducible?

`01-read.R`, `02-munge.R`, `10-prepare.R`, `20-model.R`

## Reproducible and repeatable, but fast?

`script.R` or `analysis.Rmd`, always run the entire pipeline

**Comment by krlmlr** [comment]
@wlandau: Would you like to comment on the tension between three conflicting goals in data analysis projects, solved by *drake* and *remake*?

1. Run fast
1. Run reproducibly
1. Easy to amend

## Fast and reproducible, but difficult to amend

Example: Waterfall process

## Fast and amendable, but reproducible?

`01-read.R`, `02-munge.R`, `10-prepare.R`, `20-model.R`

## Reproducible and amendable, but fast?

`script.R` or `analysis.Rmd`, always run the entire pipeline

**Comment by krlmlr** [comment]
As in:

![drake-conflicting 1](https://user-images.githubusercontent.com/1741643/36952281-fa196ae2-200d-11e8-9a7a-53250ed76f55.png)

**Comment by wlandau** [comment]
# Conflicting goals in data analysis projects

I think these concepts are a great way to frame the problem.

### Reproducibility

I think [these comments](https://github.com/ropensci/drake#reproducibility-with-confidence) hold true for both `drake` and `remake`.

### Amendable

If you change the workflow plan, `drake` and `remake` automatically figure out what needs to run during the next `make()`. This takes a lot of the pain out of amending your work mid-project. Without a Make-like tool, it is hard to pick apart the project and manually (re)run the affected components. In other words, you no longer need to have a tradeoff between reproducibiliy (running from scratch) and amendability.

### Speed

Maybe we should talk about scalability instead of speed. There are some cases where the overhead of `drake` and `remake` makes things a bit slow, and especially with staged parallelism, and the hpc features of `drake` need work. On the other hand, `drake` and `remake` are definitely fast in the sense that up-to-date work is skipped. 

# Other approaches

### Waterfall processes

I am unfamiliar, so I cannot comment

### report.Rmd

I agree with the placement in the Venn diagram: https://github.com/ropensci/drake#knitr

### 01-download.R, 02-munge.R, etc.

Again, I agree with the placement.

- Speed: outside a kntir report, you can use HPC much more easily.
- Amendability: the modularity of different scripts helps. For example, if you only change 20-model.R, you know you don't need to rerun 01-download.R.
- Lack of reproducibility: without an overarching build system, there is no guarantee that the output matches the code it came from. I would also add that any HPC is tangled up in the content of the scripts themselves, whereas `drake` takes care of it all for you, making the code more readable and thus more reproducibile.

**Comment by krlmlr** [comment]
Thanks.

The way I understand waterfall you'd work exclusively on `01-download.R` until it's done. And then you don't go back. (Maybe `02-munge.R` is handled by a different team, and there's exactly one handover because the costs are nonzero.)

I did mean "fast" in the sense of skipping work that's done. Scalability feels orthogonal, maybe we just mention it as a bonus feature?

**Comment by wlandau** [comment]
> The way I understand waterfall you'd work exclusively on 01-download.R until it's done. And then you don't go back. 

Makes sense now. Seems like the natural way to complete the two-way intersections.

> I did mean "fast" in the sense of skipping work that's done. Scalability feels orthogonal, maybe we just mention it as a bonus feature?

Sure.

**Comment by krlmlr** [comment]
Thanks. Added scalability on a second slide in the second part (https://goo.gl/DcDdrX). I'll need to clean up my repos, eventually these slides will reappear here.
